# 
name: Repository events
on: [push, pull_request, issues]
jobs:
  checkout-tests:
    runs-on: ubuntu-latest
    steps:
      - name: list some stuff
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4
      
      