# 
name: Repository events
on: 
  push:
    branches:
      - main
      - "feature/*"
      - "!feature/featA" # not going to run if the exclamation mark is there
  pull_request:
      types: [opened]
jobs:
  checkout-tests:
    runs-on: ubuntu-latest
    steps:
      - name: list some stuff
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4
      
      