# 
name: Checkout
on: push
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - name: checkout-with-action
        uses: actions/checkout@v3
      - name: List files after
        run: ls -a
      
      