# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
name: First Workflow
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Windows string"
      - name: Error step
        run: does not exists