# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
name: Workflow commands
on: push
jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting error messagew with params
        run: echo "::error title, file=app.js, line=2, endLine:3, col-5 endColumn=7::MissingSemicolon"
      - name: Setting debug messagew with params
        run: echo "::debugtitle, file=app.js, line=2, endLine:3, col-5 endColumn=7::MissingSemicolon"
      - name: Setting warning messagew with params
        run: echo "::warning title, file=app.js, line=2, endLine:3, col-5 endColumn=7::MissingSemicolon"
      - name: Setting notice messagew with params
        run: echo "::notice title, file=app.js, line=2, endLine:3, col-5 endColumn=7::MissingSemicolon"